name: Sync release to changes
on:
  workflow_dispatch:
jobs:
  sync-branch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ${{ github.sha }} update from release
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: release
          target_branch: changes
          github_token: ${{ github.token }}
